# Generated by Django 5.2 on 2026-08-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tasks_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]
