# Generated by Django 5.2 on 2026-08-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['created_at'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='users',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
